### ISSUE TITLE
why not working on js.bin?

### ISSUE THREAD

**Issue by kimkyeseung** [cojdev/lowpoly#1]
I copied your code on codepen.io(<https://codepen.io/charleso>) onto the jsbin.com.
I don't know why it doesn't work on jsbin.
I copied html, css, js all.
should I need to add something library?
plz le me know.
I need your help

here is <https://jsbin.com> link

**Comment by cojdev** [comment]
Hi, apologies for not looking into this but the codebase has changed so much since then so I'm closing this issue.
